### ISSUE TITLE
可以通过param自定义显示位数么

### ISSUE THREAD

**Issue by wlt233** [journey-ad/Moe-Counter#2]
看代码里好像是 `length = PLACES` 写死的，可以考虑用 param 自定义显示位数么🤔

**Comment by journey-ad** [comment]
可能会影响到数据库数值上限，需要再研究下

**Comment by MarkusJoe** [comment]
往数据库只存当前访问量例如我访问了`345`次就存`500`次进去，读数据库的时候用请求参数里的length减去数据库数据的长度例如length是`7` 用7-3，`3`是`345`的数据长度，得到的结果为4，就得到了全部的结果`0000345`， 下面有一段用python实现的代码

```python

def main(length: int, count: int):
    """
    拼接出完整的字符串
    :param length:
    :param count:
    :return final_number
    """
    zero_count = length - len(str(counr))  # len()方法不能对整形进行操作所以需要转换为字符串
    final_number = '0' * zero_count + str(count)
    print(final_number)
    return final_number
 
main(7, 345)  #7是请求参数的值， 345是数据库读取到的访问次数

```

如果我没理解错意思的话。

**Comment by journey-ad** [comment]
现在可以通过 `padding` 参数指定显示位数
Now you can specify the display digits through the `padding` parameter.

https://count.getloli.com/

**Comment by RTAkland** [comment]
我去四年了终于复活了

**Comment by 1834423612** [comment]
看到我之前提的一个改进php版的issue关闭了还以为是自动的，没想到进来后发现是项目复活了（好耶
还以为作者弃坑了😂
