### ISSUE TITLE
大佬，基于您的项目我重新开发了PHP版本的，望指点些问题

### ISSUE THREAD

**Issue by 1834423612** [journey-ad/Moe-Counter#24]
项目链接附上：
https://github.com/1834423612/Moe-counter-PHP

**Comment by MCBBC** [comment]
瞅瞅俺的awa https://github.com/MCBBC/Moe-counter/

**Comment by 1834423612** [comment]
> 瞅瞅俺的awa https://github.com/MCBBC/Moe-counter/

我觉得彳亍，正合我意😝( ͡° ͜ʖ ͡°)✧

**Comment by MCBBC** [comment]
> > 瞅瞅俺的awa https://github.com/MCBBC/Moe-counter/
> 
> 我觉得彳亍，正合我意😝( ͡° ͜ʖ ͡°)✧

awa

**Comment by ApliNi** [comment]
一个更简单的qwq! https://github.com/ApliNi/Moe-counter-PHP/

**Comment by 1834423612** [comment]
> 一个更简单的qwq! https://github.com/ApliNi/Moe-counter-PHP/

(o゜▽゜)o☆
