### ISSUE TITLE
计数会不定时重置

### ISSUE THREAD

**Issue by breathiness** [journey-ad/Moe-counter#27]
直接使用Demo里的链接在刷新几次之后就会重置计数，请问这个是什么原因？这个是必须自己搭建才行吗？

![](https://count.getloli.com/get/@breathiness)

**Comment by journey-ad** [comment]
Demo 站点此前为了防止并发过高导致 DB 连接失败做了一层延迟写入，同时引入了这个 Bug，已定位到原因并修复

**Comment by breathiness** [comment]
谢谢，已经可以正常使用
