### ISSUE TITLE
I am about to go insane

### ISSUE THREAD

**Issue by ShockedCoder** [journey-ad/Moe-counter#34]
I've tried and tried for the past three days, and I still can't figure out what the hell this thing does.
I'm literally about to go insane, I'm begging someone to help me figure this shit out.

**Comment by jimmyli56** [comment]
What do you need help with? I was able to incorporate the counter into my GitHub profile fairly easily.

**Comment by jimmyli56** [comment]
It's a counter that increases its count every time the site that contains the image is accessed. Here's a video to show you what I mean: 

https://user-images.githubusercontent.com/27116171/195775768-42afa860-06a6-40e3-ac0e-167bbb7666a4.mov

**Comment by jimmyli56** [comment]
Most sites, like mine, uses it to count pageviews

**Comment by ShockedCoder** [comment]
Ahaaa, aight thx.

**Comment by jimmyli56** [comment]
No problem! Glad I was able to help you get unconfused.

**Comment by snowman** [comment]
what the counter increase? where does it store the page views? Like in GitHub, it seems only possible to host *static* files like HTML/CSS/JS, where is the database?

**Comment by snowman** [comment]
In the plain-text mode, the image url of `Moe-Counter` is `https://count.getloli.com/get/@Moe-counter.github`:

https://github.com/journey-ad/Moe-Counter/blob/81936a98836dcae728aac3bdce7d649b43fc94b0/Readme.md?plain=1#L1-L5

But when open in markdown HTML mode, the URL become anonymous:

  `https://camo.githubusercontent.com/fdf42c3905748fe5df5dc8cdb3b52ab23764c496404280f9655cbcb104da7951/68747470733a2f2f636f756e742e6765746c6f6c692e636f6d2f6765742f404d6f652d636f756e7465722e676974687562`

<hr>

[about-anonymized-urls](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls)
> Camo generates an anonymous URL proxy for each file which hides your browser details and related information from other users.
