### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by Marweey** [journey-ad/Moe-Counter#35]
Plzzzzzzzzzzzzzzzzz，fix it!!!!!!

**Comment by Fijxu** [comment]
I am running a mirror here 
https://count.ayaya.beauty
Feel free to use. There are many issues about the main site going down so...
I will keep up this mirror up for as long as I want. I used it personally for several weeks already

**Comment by Marweey** [comment]
Idk if you are a chinese, but this mirror seems outside that WALL(nam saying?). Hopefully that I can use count.getloli inside of the WALL.
55555555555555

**Comment by Fijxu** [comment]
No, i'am not chinese :p
Anyways this mirror is running in Chile and not USA (like the original count.getloli.com) if you care about that

**Comment by Marweey** [comment]
Thanks for your reply. I can visit [count.getloli.com] but cant visit [count.ayaya.beauty] without VPN. Im using this counter on my own blog website in China, Its impossible that everyone who visit my website is running their VPN so that they can see those cute getlolis. Thus I realllllllllllllllllllly hope that you can fix count.getloli.com!

**Comment by Fijxu** [comment]
OH SHIT MAN I JUST REMEMBER I HAD CHINA BLOCKED IN MY FIREWALL LOLL. Let me fix it

**Comment by Marweey** [comment]
Niceeeeeeeeeeeeeeeeeeeeee! I can reach it now!!!!!!!!!!!!!!!yessssssssssssss! Thank you!!!!!!!!!!!!!

**Comment by Marweey** [comment]
website down again QAQ~

**Comment by Sadamingh** [comment]
Hi @Fijxu, the [count.ayaya.beauty](https://count.ayaya.beauty/) mirror's down. Can you help with that or are you still maintaining it?

**Comment by Fijxu** [comment]
@Marweey @Sadamingh Fixed, sorry for the trouble, i updated and restarted the server and something failed :p

**Comment by Sadamingh** [comment]
Thanks a lot Fijxu

**Comment by Sadamingh** [comment]
Hi Fijxu @Fijxu, it's down again. Thank you for your time.

**Comment by Fijxu** [comment]
> Hi Fijxu @Fijxu, it's down again. Thank you for your time.

Fixed again, i forgot to pay the VPS (well, sometimes I don't feel like paying for it because it's a crappy server)

**Comment by Sadamingh** [comment]
> > Hi Fijxu @Fijxu, it's down again. Thank you for your time.
> 
> Fixed again, i forgot to pay the VPS (well, sometimes I don't feel like paying for it because it's a crappy server)

TY. Please let me know if you want to modify or rebuild the VPS server. I'm not sure if it's open source but let's see if I can help you with that. So just let me know 🤗

**Comment by Marweey** [comment]
@Fijxu China has been blocked in your firewall loll again?QAQ~~Thanks for your time!

**Comment by Marweey** [comment]
Hi @Fijxu , China has been blocked in your firewall loll again? I can't reach count.ayaya.beauty.Thanks for your time!

**Comment by Marweey** [comment]
@Fijxu It seems like count.ayaya.beauty down again. I check it and found "Connect time out" all over the world. Thanks for your time!

**Comment by Fijxu** [comment]
> @Fijxu It seems like count.ayaya.beauty down again. I check it and found "Connection timed out" all over the world. Thanks for your time!

Yep, i know, I am migrating the OS from Ubuntu to NixOS. No data was lost so it will available in 2 days or more ;)
