### ISSUE TITLE
Demo cannot be used

### ISSUE THREAD

**Issue by Ares-Chang** [journey-ad/Moe-Counter#41]
hi, is this project still under maintenance? I found today that [https://replit.com/](https://replit.com/) seems to have changed its content.

**Comment by journey-ad** [comment]
Demo site has been restored.
The code used for the demo has been adjusted to fit the environment of Replit, and I will merge the changes back into the repository later.

**Comment by journey-ad** [comment]
resolved.

**Comment by OrageKK** [comment]
demo站点最近又挂了
