### ISSUE TITLE
This project has received too many requests, please try again later.

### ISSUE THREAD

**Issue by shaoting0730** [journey-ad/Moe-Counter#59]
This project has received too many requests, please try again later. 麻烦修复下

**Comment by zhulinyv** [comment]
You can deploy it by yourself on replit, your own server, codespaces, etc.

After successfully deploying, you can edit the **count.db** file to revert the counts.

**Comment by liuly0322** [comment]
If you only use it to count page views, you can try [Moe-Counter-Busuanzi](https://github.com/liuly0322/moe-counter-busuanzi), which does not need a server to deploy. (While currently it only supports the default theme.) About ~10KB size.

```html
<script type="module">
import { generateCounterImage, fetchBusuanziCounter } from 'https://cdn.jsdelivr.net/npm/moe-counter-busuanzi@1.0.2/+esm';

const busuanziResult = await fetchBusuanziCounter();
const counterSVGString = generateCounterImage(busuanziResult.page_pv);
document.getElementById("counter").innerHTML = counterSVGString;
</script>
```

**Comment by shaoting0730** [comment]
ok~ 感谢 @liuly0322
