### ISSUE TITLE
请教svg文件动态改变的原理

### ISSUE THREAD

**Issue by zhuoqun-chen** [journey-ad/Moe-counter#6]
我按照您提供的demo参考网站 http://count.getloli.com/，在我的html文件中写入" <img src="https://count.getloli.com/get/@:name" alt=":name" / "后，用chrome浏览器打开html文件，可以看到那个萌妹svg图片，点击刷新或是重新打开该文件后，svg图片上的数字在有序的递增，我不明白是怎么做到可以动态返回我一张动态变化着的svg图片的，萌新求指点~~

**Comment by journey-ad** [comment]
显示的 svg 不是静态的图片文件，是用 nodejs 渲染输出的
原理就是一个计数器，每次访问都会+1，然后根据计数器的数字渲染相应的 svg
