### ISSUE TITLE
moe-counter服务疑似挂了

### ISSUE THREAD

**Issue by suisbuds** [journey-ad/Moe-Counter#62]
### Bug Report
1. [Demo网站无法运行](https://count.getloli.com/)，提示：This project has received too many requests, please try again later.
2. github readme上使用的API服务疑似挂掉，参考：[![](https://count.getloli.com/get/@xxx.github.readme)](https://count.getloli.com/)

**Comment by suisbuds** [comment]
12:06时服务恢复

**Comment by suisbuds** [comment]
12:09时又挂了，可能是网站被攻击了？

**Comment by journey-ad** [comment]
目前用的glitch的免费服务，访问量大就会被限制
