### ISSUE TITLE
[Theme]: Love and Deep Space

### ISSUE THREAD

**Issue by JinxuanChen03** [journey-ad/Moe-Counter#65]
### Tips

- [X] I have read and understood the tips above

### Theme Name

Love and Deep Space

### Preview and ZIP file
![预览](https://github.com/user-attachments/assets/746c9898-e0b0-4f8a-8e0f-0b442a9d6d23)
[LoveAndDeepSpace.zip](https://github.com/user-attachments/files/17469431/LoveAndDeepSpace.zip)

**Comment by JinxuanChen03** [comment]
我是不是应该把preview放在外面
![预览](https://github.com/user-attachments/assets/85bfa3d1-3f40-4323-9634-17e59388b051)

**Comment by journey-ad** [comment]
Thanks for sharing, the theme is now available.

**Theme name**:
`love-and-deepspace`

**Preview**:
[![love-and-deepspace](https://count.getloli.com/@demo?theme=love-and-deepspace)](https://count.getloli.com/@demo?theme=love-and-deepspace)
