### ISSUE TITLE
[Feature] 将项目配置方式由配置文件更改为直接使用环境变量配置

### ISSUE THREAD

**Issue by Hoshino-Yumetsuki** [journey-ad/Moe-Counter#66]
由于 Moe-Counter 需要修改的配置项并不多，而且在各种平台进行私有部署时并不方便修改 config ，所以建议将配置修改为直接使用环境变量进行配置。

如

- DATABASE = mongodb | sqlite
- MONGODB_URI = 
- APP_PORT = 3000

同时，可以通过调整配置项优先级来确保对旧配置的兼容性，如在有环境变量的情况下优先使用环境变量

**Comment by journey-ad** [comment]
已将配置文件更换为 `.env` 文件，等效于环境变量 https://github.com/journey-ad/Moe-Counter/commit/e4132e0ef1881f421964d7293bcb9f81c4523e32
