### ISSUE TITLE
Dark theme is not good

### ISSUE THREAD

**Issue by akku1139** [journey-ad/Moe-Counter#67]
Dark
![image](https://github.com/user-attachments/assets/07aa73f3-e39a-4242-82e7-c6c3c2f39571)
![image](https://github.com/user-attachments/assets/58bb84fc-208f-4a70-9c69-c88ab2b864af)

Light
![image](https://github.com/user-attachments/assets/7c2b3d78-a11a-4605-8852-fe2e1718e085)
![image](https://github.com/user-attachments/assets/daf979d1-bc49-474a-aeb4-b015c13331e5)

**Comment by akku1139** [comment]
Dark theme reduces visibility.

**Comment by journey-ad** [comment]
The design reduces brightness and contrast on dark backgrounds. You can disable it with `darkmode=0`. See https://count.getloli.com

**Comment by akku1139** [comment]
Thank you. I was surprised because it was a sudden change in specifications.
