### ISSUE TITLE
大佬 请教一下关于统计数被重置的问题

### ISSUE THREAD

**Issue by Yakumo-Yukari** [journey-ad/Moe-counter#8]
按照教程允许在 repl.it 上  配置里用的 sqlite数据库  但是发现 网站使用后每天统计数字会被重置从零开始  有时候同一天里也会被重置 从新统计  请问是什么原因呢？

**Comment by journey-ad** [comment]
repl.it 的本地文件策略比较迷，初期我也用的 sqlite，后来发现进度会丢失，就改用 mongodb 了，用的是 mongodb.com 的免费额度
repl.it 似乎也提供了可选的数据库服务，可以研究下

**Comment by Yakumo-Yukari** [comment]
![20210125123630](https://user-images.githubusercontent.com/12076232/105662169-069a0180-5f0a-11eb-9069-73b49181188a.png)

请问下 这个连接是怎么选的
